apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify1
  namespace: internal
  description: My RESTful API
spec:
  type: openapi
  lifecycle: production
  system: my-system
  owner: my-team
  definition:
    $text: https://github.com/sunilthemaster/openapi-directory/blob/main/APIs/spotify.com/1.0.0/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify1
  namespace: external
  description: My RESTful API
spec:
  type: openapi
  lifecycle: production
  system: my-system
  owner: my-team
  definition:
    $text: https://github.com/sunilthemaster/openapi-directory/blob/main/APIs/spotify.com/sonallux/2023.2.27/openapi.yaml
